### ISSUE TITLE
Navbar - Adicionar informações de curso

### ISSUE THREAD

**Issue by eudin94** [IFRS-Campus-Restinga/2024-2-Aproveitamento-Componentes#79]
Melhorar as opções de navegabilidade da Navbar.
Quem pegar essa issue, favor alinhar com o time que informações serão importantes.

@eudin94 : Ao lado da NavBar temos o nome do usuário. Minha sugestão é que quem fizer essa issue  poderia incorporar a role do usuário logado junto com o nome.

**Comment by BrunosFeijo** [comment]
Feito. Adicionado Curso na navbar
